
MainDir <- 'C:/Users/U8019357/OneDrive - UniSQ'

#=========================================================================================================================
# Parameters
#=========================================================================================================================
{
  HostUni  <- 'USQ'
  Projects <- '2024.04.26 Short-Term Forecast for Irrigation Management'
  RunSet   <- '2024.05.26 2Lead-4P-1Z-2DelayFrac-22Treat-3Soil-2N'
  RunNames <- c('2024.05.28 Run2-50Rep')
  
  
  Bundle    <- T
  Upload    <- T
  UploadR   <- F   # Upload all R scripts (shared and project)?
  RunOnServ <- T
  
  # At least one of these must be non-NULL
  NJobs      <- 6
  SimsPerJob <- NULL
  
  # If SimilarJobs=TRUE, it assumes all jobs will run all simulations but with different inputs, which are generated by PreProcR.
  SimilarJobs <- F
  
  NewSetts   <- data.frame(CPU=20,Mem='40GB',WallT='12:00:00')
  MoreCPUs   <- 1  # The number of CPUs requested more than the number APSIM is going to use 
  # to avoid exceeding maximum CPU number on the cluster
  
  # The R script that runs before simulations are run (i.e., pre-processing).
  PreProcR <- "C:/Users/U8019357/OneDrive - UniSQ/00_Projects/2024.04.26 Short-Term Forecast for Irrigation Management/01_R/APSIMTemplates/PreAPSIMRun.R"
  
  # The arguments that are passed to PreProcR.
  PreProcRArgs <- c(SimilarJobs)
  
  # The R script that runs after simulations are complete (i.e., post-processing).
  PostProcR <- NULL
  
  # The arguments that are passed to PostProcR
  PostProcRArgs <- NULL
  
  # The files that are needed by either PreProcR or PostProcR
  PrePostFiles <- c("C:/Users/U8019357/OneDrive - UniSQ/00_Projects/2024.04.26 Short-Term Forecast for Irrigation Management/01_R/APSIMTemplates/Treatments.xlsx",
                    "C:/Users/U8019357/OneDrive - UniSQ/00_Projects/2024.04.26 Short-Term Forecast for Irrigation Management/04_Data/Soils/SoilsModified_2024.05.28.apsimx",
                    "C:/Users/U8019357/OneDrive - UniSQ/00_Projects/2024.04.26 Short-Term Forecast for Irrigation Management/04_Data/Weather Files/Modified/MetData.RData")
  
  ProjectGroup <- '459040_1008724_APSIMSesame'
  Singularity  <- '${SIFDIR}/ApsimXbcgit.sif' # '${SIFDIR}/ApsimXmngit.sif'
  ApsimExec    <- 'Models'
  
  # If PlayList=NULL and SimilarJobs=FALSE, a new Playlist called "TemporaryPL" will be added and run.
  # If PlayList!=NULL and SimilarJobs=FALSE, the following Playlist must exist and will be run.
  Playlist <- NULL
  
  # If non-NULL, Models.exe will use '--apply' command. ConfigFile must be generated by PreProcR.
  ConfigFile <- 'Config.txt'
  
  MainDir    <- 'C:/Users/u8019357/OneDrive - UniSQ/'
  
  if (dir.exists('C:/Users/u8019357/Documents/Repository/ApsimClassic')) {
    BundleConsolePath <- "C:/Users/U8019357/OneDrive - UniSQ/Documents/Repository/APSIMNextGen/bin/Debug/net6.0/Models.exe"
  } else {
    BundleConsolePath <- "C:/Users/U8019357/OneDrive - UniSQ/Documents/Repository/APSIMNextGen/bin/Debug/net6.0/Models.exe"
  }
}
#========================================================================================================
# Sources and Folders
#========================================================================================================
{
  source(paste(MainDir,'00_Projects/SharedScripts/MySourceProject.R',sep='/'))
  Dir <- SetupProject(MainDir=MainDir,Project=Projects[1],Run=NULL,RunSet=NULL,SharedScripts=c('MyFunctions.R','MyApsim.R'))
}
#========================================================================================================
# Bundle and Run
#========================================================================================================

APSIM_Bundle(HostUni=HostUni,MainDir=MainDir,Projects=Projects,RunSet=RunSet,RunNames=RunNames,IsApsimNG=T,Bundle=Bundle,
             Upload=Upload,UploadR=UploadR,NJobs=NJobs,SimsPerJob=SimsPerJob,RunOnServ=RunOnServ,NewSetts=NewSetts,MoreCPUs=MoreCPUs,
             BundleConsolePath=BundleConsolePath,Singularity=Singularity,ProjectGroup=ProjectGroup,ApsimExec=ApsimExec,
             PreProcR=PreProcR,PreProcRArgs=PreProcRArgs,PostProcR=PostProcR,PostProcRArgs=PostProcRArgs,PrePostFiles=PrePostFiles,
             SimilarJobs=SimilarJobs,Playlist=Playlist,ConfigFile=ConfigFile)


