"""
Azure ML Model Registration Script

This script registers a trained machine learning model in an Azure Machine
Learning workspace using artefacts and evaluation metrics generated by a
previous pipeline step.

Workflow
1. Parse command line arguments containing model artefact and evaluation paths.
2. Load evaluation metrics produced during the model evaluation stage.
3. Determine the Azure ML model type (MLflow or custom model).
4. Register the trained model in the Azure ML Model Registry.
5. Attach evaluation metrics as model tags for traceability.
6. Write a registration summary JSON file for downstream pipeline stages.

Purpose
Provides a reproducible model registration step within an MLOps workflow.
It links training outputs, evaluation metrics, and the Azure ML model
registry so that validated models can be tracked, versioned, and promoted
to deployment stages.

Inputs
--train_output_dir
    Directory containing the trained model artefacts produced by the
    training pipeline step.

--eval_output_dir
    Directory containing evaluation metric files generated by the
    evaluation step. Each metric is expected to be stored as a text file
    named <metric_name>.txt (e.g. eval_r2.txt, eval_mse.txt).

--model_name
    Name under which the model will be registered in the Azure ML
    workspace.

--is_mlflow
    Flag indicating whether the model follows MLflow format.
    "true" registers the model as an MLflow model, otherwise it is
    registered as a custom Azure ML model.

--register_output_dir
    Directory where registration metadata and summary files will be saved.

Outputs
registration_summary.json
    A summary file containing:
        - model_name
        - model_version
        - model_type
        - training output location
        - evaluation output location
        - evaluation metrics

Dependencies
- azure-ai-ml SDK
- Custom Azure ML authentication helper (get_ml_client)

Typical Use Case
Executed after a training and evaluation pipeline step to register a
validated model in the Azure ML Model Registry. The resulting summary
artefacts can be used by CI/CD pipelines for model promotion,
deployment, or governance workflows.
"""


import argparse
import json
import os

from azure.ai.ml.entities import Model

from utils import get_ml_client


def read_metric_file(eval_output_dir: str, metric_name: str) -> str:
    """
    Read a metric value written by the evaluation step.
    Expected file name pattern: <metric_name>.txt
    """
    # Build expected metric file path
    metric_path = os.path.join(eval_output_dir, f"{metric_name}.txt")

    # Fail clearly if the metric file is missing
    if not os.path.exists(metric_path):
        raise FileNotFoundError(f"Metric file not found: {metric_path}")

    # Read and return the stored metric value
    with open(metric_path, "r", encoding="utf-8") as f:
        return f.read().strip()


def main(args):
    # Ensure output directory for registration artefacts exists
    os.makedirs(args.register_output_dir, exist_ok=True)

    # Create authenticated Azure ML client
    ml_client = get_ml_client()

    # Load evaluation metrics produced by the evaluation step
    eval_r2 = read_metric_file(args.eval_output_dir, "eval_r2")
    eval_mse = read_metric_file(args.eval_output_dir, "eval_mse")

    # Choose Azure ML model type based on registration mode
    model_type = "mlflow_model" if args.is_mlflow.lower() == "true" else "custom_model"

    # Define model registration payload
    model = Model(
        name=args.model_name,
        path=args.train_output_dir,
        type=model_type,
        tags={
            "eval_r2": eval_r2,
            "eval_mse": eval_mse,
        },
    )

    # Register model in Azure ML
    registered_model = ml_client.models.create_or_update(model)

    # Build summary of registration outputs
    summary = {
        "model_name": registered_model.name,
        "model_version": registered_model.version,
        "model_type": model_type,
        "train_output_dir": args.train_output_dir,
        "eval_output_dir": args.eval_output_dir,
        "eval_r2": eval_r2,
        "eval_mse": eval_mse,
    }

    # Persist registration summary for downstream use
    summary_path = os.path.join(args.register_output_dir, "registration_summary.json")
    with open(summary_path, "w", encoding="utf-8") as f:
        json.dump(summary, f, indent=2)

    # Print registration result summary
    print("Model registration complete")
    print(f"Model name: {registered_model.name}")
    print(f"Model version: {registered_model.version}")
    print(f"Summary written to: {summary_path}")


if __name__ == "__main__":
    # Parse command line arguments
    parser = argparse.ArgumentParser()
    parser.add_argument("--train_output_dir", type=str, required=True)
    parser.add_argument("--eval_output_dir", type=str, required=True)
    parser.add_argument("--model_name", type=str, required=True)
    parser.add_argument("--is_mlflow", type=str, default="false")
    parser.add_argument("--register_output_dir", type=str, required=True)
    args = parser.parse_args()

    # Execute model registration workflow
    main(args)